[SUI] [Tabs] Proper fix in SUI for icons in tabs -> SUI-125
wpmudev/shared-ui pull request #312
Opened 2021-06-21 18:28 UTC by Gowtham369

Added a query to make parent active onClick on it's child span(icon-selector-content)

2021-06-24 02:22 UTC, iamleigh requested changes

2021-06-24 02:22 UTC, iamleigh commented on assets/js/shared-ui/side-tabs.js
> +			$span     = $this.parent( 'label > span' ),
@Gowtham369 some times the best solution is the simplest one. There's no need to add all this code to prevent `aria-selected` from being added to the icon instead of the tab. You can solve all this by simply adding `pointer-events: none` to any additional markup (that's not text) added inside the tab.

2021-06-24 02:22 UTC, iamleigh commented on CHANGELOG.md
> +- [Fix] Icons(span) inside the tab-itmes are made clickable.
@Gowtham369 actually, the issue was related to icon alignment inside the tab.

2021-06-24 17:45 UTC, Gowtham369 commented on assets/js/shared-ui/side-tabs.js
> +			$span     = $this.parent( 'label > span' ),
Actually that span is the only related code.
My bad that I added aria-side-tabs issue code also in to this.
Will clear this.
I have tried adding `pointer-events:none` to the span or anything that would be inside the button, but did not work.
Will try to explore more ways.

2021-06-29 21:54 UTC, iamleigh requested changes

2021-06-29 21:54 UTC, iamleigh commented on assets/js/shared-ui/side-tabs.js
> +			//This is to resolve the issue(SUI-125->https://incsub.atlassian.net/browse/SUI-125) To activate parent element while even clicking on span(icon)
@Gowtham369 there's a new comment but there's no new code to relate. Is this comment correct or did you forget to remove it?

2021-06-29 21:54 UTC, iamleigh commented on assets/js/shared-ui/side-tabs.js
> +			$alllabels.children().css("pointer-events","none")
@Gowtham369 there's no need to use JS. Use CSS instead (not inline CSS through JS but adding code through SCSS).

2021-07-12 02:02 UTC, iamleigh approved these changes

2021-07-12 02:04 UTC, merged