✨ enhancement(buttons): updated buttons markup on the showcase
wpmudev/shared-ui pull request #440
Opened 2022-01-07 05:13 UTC by creador-dev

2022-01-18 07:43 UTC, iamleigh requested changes

2022-01-18 07:43 UTC, iamleigh commented on assets/scss/showcase/components/_element-code-block.scss
> +		// }
@creador-dev why did you comment on these lines of code instead of erasing them? What is it doing?

2022-01-18 08:09 UTC, creador-dev commented on assets/scss/showcase/components/_element-code-block.scss
> +		// }
I think i was testing it whether it breaks something or not and then forgot to delete it. I will make the changes.

2022-01-21 20:41 UTC, iamleigh approved these changes

2022-01-21 20:43 UTC, merged