enhance(insert variables): removed selected value in insert variables
wpmudev/shared-ui pull request #468
Opened 2022-02-28 12:19 UTC by creador-dev

2022-02-28 17:15 UTC, iamleigh requested changes

2022-02-28 17:15 UTC, iamleigh commented on assets/js/showcase/pages/insert-variables.js
> +				select.val( null ).trigger( 'change' );
@creador-dev why do you need to add again this line of code? If it was already added to the `select2.js` file, there's no need to add it again.

2022-03-01 04:06 UTC, creador-dev commented on assets/js/showcase/pages/insert-variables.js
> +				select.val( null ).trigger( 'change' );
@iamleigh this code removes selected item when option changes otherwise it will work only for the first time.

2022-03-04 02:06 UTC, iamleigh requested changes
@creador-dev review again your changes, please. Remember, if developers use the `SUI.select.initVars` function they need to get everything from it. There's no need to re-add the clear function again because if it doesn't work right now on the showcase it won't for sure on the plugins. Dig a bit more and try a better solution.

2022-03-09 02:24 UTC, iamleigh requested changes

2022-03-09 02:24 UTC, iamleigh commented on page-insert-variables.html
> +						<option value=""></option>
@creador-dev We shouldn't add an empty `option` unless we actually need it or there's some placeholder we need to use and in this case, Insert Variables component doesn't need this.

2022-03-09 02:24 UTC, iamleigh commented on assets/js/showcase/pages/insert-variables.js
> +		}
@creador-dev I tried your changes on the code and even it looks fine, is not working. Try triggering the change when the dropdown closes.

2022-03-13 18:26 UTC, iamleigh requested changes

2022-03-13 18:26 UTC, iamleigh commented on assets/js/showcase/pages/insert-variables.js
> +				select.val( null ).trigger( 'change' );
@creador-dev why not try clearing the selected value when the dropdown closes? You will simplify the code, and also we make sure to have the best experience for screen reader users.

2022-03-17 00:07 UTC, iamleigh approved these changes

2022-03-17 00:08 UTC, merged