🐛 fix(select): select displays as usual when monochrome mode is enabled
wpmudev/shared-ui pull request #474
Opened 2022-03-10 05:43 UTC by creador-dev

2022-03-13 22:56 UTC, iamleigh requested changes

2022-03-13 22:56 UTC, iamleigh commented on assets/js/showcase/globals/admin-bar.js
> +					body.removeClass( 'sui-select-accessible' );
@creador-dev this is not a viable solution. This file is to simulate some actions on the showcase but won't produce any real fix when the SUI package gets installed in a plugin. Please, move this action to be part of the library, like inside `select2.js` file.

2022-03-13 22:56 UTC, iamleigh commented on assets/scss/shared-ui/_color-accessibility.scss
> +			background-color: $accessible-dark !important;
@creador-dev, more elements need to be highlighted with black or white, depending on the case, for the component to be appropriately accessible—for example, the dropdown border and unselected items.

2022-03-14 11:35 UTC, creador-dev commented on assets/js/showcase/globals/admin-bar.js
> +					body.removeClass( 'sui-select-accessible' );
We have to use this solution to show select 2 style in showcase. I have added js in select2.js for sui accessible color to work in plugin.

2022-03-14 11:35 UTC, creador-dev commented on assets/scss/shared-ui/_color-accessibility.scss
> +			background-color: $accessible-dark !important;
i have added the changes accrodingly.

2022-03-20 03:15 UTC, iamleigh approved these changes

2022-03-20 03:15 UTC, merged