🐛 fix(settings-box): fixed rtl layout for settings
wpmudev/shared-ui pull request #475
Opened 2022-03-10 06:26 UTC by creador-dev

2022-03-13 23:11 UTC, iamleigh requested changes

2022-03-13 23:11 UTC, iamleigh commented on assets/scss/shared-ui/_code-snippet.scss
> +			left: 15px;
@creador-dev, PRs are dedicated to a specific element, and in this case, this pull request focuses on the "settings box" component.

2022-03-13 23:11 UTC, iamleigh commented on assets/scss/shared-ui/_toggles.scss
> +@include body-class($wrap: true, $rtl: true) {
@creador-dev, PRs are dedicated to a specific element, and in this case, this pull request focuses on the "settings box" component.

2022-03-13 23:11 UTC, iamleigh commented on assets/scss/shared-ui/_utility.scss
> +@include body-class($wrap: true, $rtl: true) {
@creador-dev, PRs are dedicated to a specific element, and in this case, this pull request focuses on the "settings box" component.

2022-03-22 05:55 UTC, creador-dev commented on assets/scss/shared-ui/_box-settings.scss
> +	.sui-box-header {
@iamleigh The tags doesn’t have any wrapper or container i add css for this it will also reflect on other pages too. What should I do in this case ?

2022-03-23 03:21 UTC, iamleigh requested changes
@creador-dev, when testing the changes on RTL mode, the second (larger) column has an unnecessary or misplaced proper padding. Please, correct this.

2022-03-24 07:17 UTC, iamleigh requested changes

2022-03-24 07:17 UTC, iamleigh commented on assets/scss/shared-ui/_box-settings.scss
> +				flex: 0 1 100%;
@creador-dev, I think it is safe to say that using flex for small screens is unnecessary and has the potential to break. Let's move into block display for small screens.

2022-03-25 00:13 UTC, iamleigh approved these changes

2022-03-25 00:14 UTC, merged