✨ new(button): updated button markup to latest.
wpmudev/shared-ui pull request #493
Opened 2022-04-08 06:24 UTC by creador-dev

2022-04-11 21:25 UTC, iamleigh requested changes

2022-04-11 21:25 UTC, iamleigh commented on page-builder.html
> +								<span class="sui-button__icon sui-icon-plus" aria-hidden="true"></span>
@creador-dev, make sure all icons in a button have the `sui-sm` class. That's the default size.

2022-04-11 21:25 UTC, iamleigh commented on page-modals.html
> +										<span class="sui-button__label sui-loading-text">Activate</span>
@creador-dev, if I am not wrong (which in this particular case, I think I am not), the `sui-loading-text` class was deprecated in the revamp.

2022-04-11 21:25 UTC, iamleigh commented on page-modals.html
> +															<span class="sui-button__loader sui-icon-loader sui-loading" aria-hidden="true"></span>
@creador-dev, again, the `sui-loading-text` class was deprecated. We should remove it. Also, don't forget to include the correct/default icon size.

2022-04-12 05:52 UTC, creador-dev commented on assets/js/shared-ui/password.js
> +						$icon   = $button.find( '> span[class^="sui-icon-"]' )
@iamleigh If i use sui-button__icon then it won't work for password field as it has "sui-button-icon".

2022-04-13 00:15 UTC, iamleigh requested changes

2022-04-13 00:15 UTC, iamleigh commented on assets/js/shared-ui/password.js
> +						$icon   = $button.find( '> span[class^="sui-icon-"]' )
@creador-dev, make a logical comparison to know if it is an icon button or a regular one. If it is an icon button use the regular method or else use `sui-buton__icon`.

2022-04-22 05:02 UTC, iamleigh approved these changes

2022-04-22 05:03 UTC, merged